Repository IRECIPE/IRECIPE-Android, pull requests merged in 2024-01, with the labels that each got.

#3 [Feat] 네이버, 카카오 로그인 구현
  IRecipe/.idea/kotlinc.xml
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/MainActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/manager/KakaoLoginManager.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/manager/NaverLoginManager.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/ApplicationClass.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/BaseActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/BaseFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/State.kt
  IRecipe/app/src/main/res/drawable/bg_login_kakao.xml
  IRecipe/app/src/main/res/drawable/bg_login_naver.xml
  IRecipe/app/src/main/res/drawable/ic_login_kakao.png
  IRecipe/app/src/main/res/drawable/ic_login_naver.png
  IRecipe/app/src/main/res/layout/activity_home.xml
  IRecipe/app/src/main/res/layout/activity_login.xml
  IRecipe/app/src/main/res/values/strings.xml
  IRecipe/build.gradle.kts
  IRecipe/settings.gradle.kts
Labels: feat, 준/김준영

#6 [Feat] DataStore 구축
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/DataStoreModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/UserDataRepositoryIml.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/User.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/UserDataRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginViewModel.kt
Labels: feat, 준/김준영

#8 [Feat] BottomNavigationBar 구축
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/RefrigeratorFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/color/bottom_nav_select.xml
  IRecipe/app/src/main/res/drawable/bg_bottom_bar.xml
  IRecipe/app/src/main/res/drawable/ic_bottom_chat.xml
  IRecipe/app/src/main/res/drawable/ic_bottom_community.xml
  IRecipe/app/src/main/res/drawable/ic_bottom_home.xml
  IRecipe/app/src/main/res/drawable/ic_bottom_mypage.xml
  IRecipe/app/src/main/res/drawable/ic_bottom_refrigerator.xml
  IRecipe/app/src/main/res/ic_bottom_home/Group 971.png
  IRecipe/app/src/main/res/layout/activity_main.xml
  IRecipe/app/src/main/res/layout/fragment_chat_bot.xml
  IRecipe/app/src/main/res/layout/fragment_community.xml
  IRecipe/app/src/main/res/layout/fragment_home.xml
  IRecipe/app/src/main/res/layout/fragment_mypage.xml
  IRecipe/app/src/main/res/layout/fragment_refrigerator.xml
  IRecipe/app/src/main/res/menu/menu_bottom_nav.xml
  IRecipe/app/src/main/res/values/colors.xml
  IRecipe/app/src/main/res/values/strings.xml
  IRecipe/app/src/main/res/values/themes.xml
Labels: feat, 준/김준영

#11 [Feat] 회원가입 단계 구현
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/User.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/SignUpActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/SignUpViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/FirstStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/LastStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/SecondStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/Util.kt
  IRecipe/app/src/main/res/anim/horizon_enter_back.xml
  IRecipe/app/src/main/res/anim/horizon_enter_front.xml
  IRecipe/app/src/main/res/anim/horizon_exit_front.xml
  IRecipe/app/src/main/res/anim/hotizon_exit_back.xml
  IRecipe/app/src/main/res/anim/none.xml
  IRecipe/app/src/main/res/drawable/bg_button_dark_gray.xml
  IRecipe/app/src/main/res/drawable/bg_button_gray.xml
  IRecipe/app/src/main/res/drawable/bg_button_high.xml
  IRecipe/app/src/main/res/drawable/bg_button_main.xml
  IRecipe/app/src/main/res/drawable/bg_button_middle.xml
  IRecipe/app/src/main/res/drawable/bg_circle_background.xml
  IRecipe/app/src/main/res/drawable/ic_arrow_bottom.xml
  IRecipe/app/src/main/res/drawable/ic_back.xml
  IRecipe/app/src/main/res/drawable/ic_base_profile.xml
  IRecipe/app/src/main/res/drawable/ic_camera.xml
  IRecipe/app/src/main/res/drawable/ic_check.xml
  IRecipe/app/src/main/res/drawable/ic_check_true.xml
  IRecipe/app/src/main/res/drawable/selector_radio_button.xml
  IRecipe/app/src/main/res/layout/activity_signup.xml
  IRecipe/app/src/main/res/layout/fragment_signup_first.xml
  IRecipe/app/src/main/res/layout/fragment_signup_last.xml
  IRecipe/app/src/main/res/layout/fragment_signup_second.xml
  IRecipe/app/src/main/res/menu/menu_age.xml
  IRecipe/app/src/main/res/values/colors.xml
  IRecipe/app/src/main/res/values/strings.xml
Labels: feat, 준/김준영

#13 [Feat]10 onboarding
  .idea/.gitignore
  .idea/IRECIPE-Android.iml
  .idea/modules.xml
  .idea/vcs.xml
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/LastStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/onboarding/OnboardingActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/onboarding/OnboardingOneFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/onboarding/OnboardingThreeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/onboarding/OnboardingTwoFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/onboarding/PageAdapter.kt
  IRecipe/app/src/main/res/drawable/bg_button_rounded.xml
  IRecipe/app/src/main/res/drawable/bg_gray_radius.xml
  IRecipe/app/src/main/res/drawable/bg_main_radius.xml
  IRecipe/app/src/main/res/drawable/bg_rounded_back.xml
  IRecipe/app/src/main/res/drawable/ic_shadow.png
  IRecipe/app/src/main/res/drawable/img_onboarding1.png
  IRecipe/app/src/main/res/drawable/img_onboarding2.png
  IRecipe/app/src/main/res/drawable/img_onboarding3.png
  IRecipe/app/src/main/res/layout/activity_onboarding.xml
  IRecipe/app/src/main/res/layout/fragment_onboarding_one.xml
  IRecipe/app/src/main/res/layout/fragment_onboarding_three.xml
  IRecipe/app/src/main/res/layout/fragment_onboarding_two.xml
Labels: feat, 뉴아/이다윤

#15 [Feat] 챗봇 구현
  .idea/workspace.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/Chat.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/bg_chat_ai_profile.xml
  IRecipe/app/src/main/res/drawable/bg_chat_receivebox.xml
  IRecipe/app/src/main/res/drawable/bg_chat_sendbox.xml
  IRecipe/app/src/main/res/drawable/bg_chat_textbox.xml
  IRecipe/app/src/main/res/drawable/ic_chat_button.png
  IRecipe/app/src/main/res/drawable/ic_chat_profile.png
  IRecipe/app/src/main/res/drawable/ic_home.png
  IRecipe/app/src/main/res/layout/fragment_chat_bot.xml
  IRecipe/app/src/main/res/layout/item_chat.xml
Labels: feat, 뉴아/이다윤

#21 [Fix] chatbot 버튼 ui 수정
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatBotActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/bg_chat_button_show.xml
  IRecipe/app/src/main/res/drawable/ic_chat_close.png
  IRecipe/app/src/main/res/layout/activity_chat_bot.xml
  IRecipe/app/src/main/res/layout/fragment_chat_bot.xml
Labels: fix, 뉴아/이다윤
