Repository IRECIPE/IRECIPE-Android, pull requests merged in 2024-02, with the labels that each got.

#24 [Fix] 챗봇 ui 수정
  IRecipe/.idea/gradle.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatBotActivity.kt
  IRecipe/app/src/main/res/layout/activity_chat_bot.xml
Labels: fix, 뉴아/이다윤

#26 [Feat] 후기 및 Q&A UI 구현
  IRecipe/.idea/gradle.xml
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/QA.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/Review.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/CommentFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/qa/QAAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/qa/QAFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/review/ReviewAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/review/ReviewFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/bg_bubble_reply.xml
  IRecipe/app/src/main/res/drawable/ic_app_mini.png
  IRecipe/app/src/main/res/drawable/ic_app_mini.xml
  IRecipe/app/src/main/res/layout/activity_main.xml
  IRecipe/app/src/main/res/layout/fragment_comment.xml
  IRecipe/app/src/main/res/layout/fragment_comment_review.xml
  IRecipe/app/src/main/res/layout/frgament_comment_qa.xml
  IRecipe/app/src/main/res/layout/item_qa.xml
  IRecipe/app/src/main/res/layout/item_review.xml
  IRecipe/app/src/main/res/values/strings.xml
  IRecipe/app/src/main/res/values/themes.xml
Labels: feat, 준/김준영

#27 [Feat] 마이페이지 ui 구현
  IRecipe/.idea/gradle.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageAlarmFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageCenterFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypagePersonalFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/bg_button_rounded_gray.xml
  IRecipe/app/src/main/res/drawable/bg_chatbot_close.xml
  IRecipe/app/src/main/res/drawable/bg_chatbot_send_btn.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_alarm.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_alert.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_center.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_logout.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_personal.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_receipe.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_rounded.xml
  IRecipe/app/src/main/res/drawable/bg_mypage_withdraw.xml
  IRecipe/app/src/main/res/drawable/ic_chat_close.png
  IRecipe/app/src/main/res/drawable/switch_selector.xml
  IRecipe/app/src/main/res/drawable/switch_thumb.xml
  IRecipe/app/src/main/res/layout/activity_chat_bot.xml
  IRecipe/app/src/main/res/layout/activity_main.xml
  IRecipe/app/src/main/res/layout/fragment_mypage.xml
  IRecipe/app/src/main/res/layout/fragment_mypage_alarm.xml
  IRecipe/app/src/main/res/layout/fragment_mypage_center.xml
  IRecipe/app/src/main/res/layout/fragment_signup_first.xml
  IRecipe/app/src/main/res/layout/mypage_withdraw.xml
  IRecipe/app/src/main/res/values/styles.xml
Labels: feat, 뉴아/이다윤

#30 [Feat] 스플래시 로고 적용 및 로그인 아이콘 추가
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/res/drawable/ic_app_brand_logo.xml
  IRecipe/app/src/main/res/drawable/ic_app_login.png
  IRecipe/app/src/main/res/drawable/ic_app_main.xml
  IRecipe/app/src/main/res/drawable/ic_app_splash.png
  IRecipe/app/src/main/res/layout/activity_login.xml
  IRecipe/app/src/main/res/mipmap-hdpi/ic_app.png
  IRecipe/app/src/main/res/mipmap-mdpi/ic_app.png
  IRecipe/app/src/main/res/mipmap-xhdpi/ic_app.png
  IRecipe/app/src/main/res/mipmap-xxhdpi/ic_app.png
  IRecipe/app/src/main/res/mipmap-xxxhdpi/ic_app.png
  IRecipe/app/src/main/res/values-v31/themes.xml
  IRecipe/app/src/main/res/values/themes.xml
Labels: feat, 준/김준영

#36 [Refactor] UI 최적화
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatBotActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/add/RefrigeratorAddFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/Util.kt
  IRecipe/app/src/main/res/drawable/bg_chat_button_show.xml
  IRecipe/app/src/main/res/drawable/ic_minus_round.xml
  IRecipe/app/src/main/res/layout/activity_chat_bot.xml
Labels: refactor, 준/김준영

#38 [Feat] Retrofit 초기 세팅
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/AndroidManifest.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/AppInterceptor.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/AppInterceptor.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/AuthInterceptor.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/UserDataRepositoryIml.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/LoginRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/SignUpRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/CheckMemberResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/LoginResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/NickDuplicationResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/login/CheckMemberService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/login/LoginService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/login/NickDuplicationService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/login/SignUpService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/User.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/SignUpActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/SignUpViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/FirstStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/LastStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/SecondStepFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/dialog/AllergyChoiceDialog.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/ApplicationClass.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/ImageUtil.kt
  IRecipe/app/src/main/res/drawable/bg_dialog_allergy.xml
  IRecipe/app/src/main/res/drawable/ic_app_mini.png
  IRecipe/app/src/main/res/layout/dialog_allergy.xml
  IRecipe/app/src/main/res/layout/fragment_signup_last.xml
  IRecipe/app/src/main/res/layout/fragment_signup_second.xml
  IRecipe/app/src/main/res/values/strings.xml
Labels: 준/김준영

#41 [Feat] 챗봇 서버 연결
  IRecipe/.idea/deploymentTargetDropDown.xml
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/AiChatDislikeRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/AiChatDislikeResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/AiChatExpiryResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/AiChatRandomResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/AiChatRefriResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service.aichat/AiChatDislikeService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service.aichat/AiChatExpiryService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service.aichat/AiChatRandomService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service.aichat/AiChatRefriService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatBotActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/PostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/SignUpViewModel.kt
  IRecipe/app/src/main/res/drawable/bg_chat_ai_profile.xml
  IRecipe/app/src/main/res/drawable/ic_chat_profile.png
  IRecipe/app/src/main/res/drawable/ic_chat_profile.xml
  IRecipe/app/src/main/res/drawable/ic_minus_round.xml
  IRecipe/app/src/main/res/layout/item_chat.xml
Labels: feat, 뉴아/이다윤

#45 [Refactor] 챗봇 viewModel 수정
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatBotActivity.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatViewModel.kt
Labels: refactor, 뉴아/이다윤

#53 [Feat] 회원정보 수정
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/chat/AiChatDislikeRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/login/FixMemberRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/login/CheckMemberResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/login/FixMemberResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/chat/AiChatDislikeService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/login/FixMemberService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/chat/ChatViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageCenterFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypagePersonalFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/RefrigeratorViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/signup/step/LastStepFragment.kt
  IRecipe/app/src/main/res/layout/fragment_mypage.xml
  IRecipe/app/src/main/res/layout/fragment_signup_first.xml
Labels: feat, 뉴아/이다윤

#54 [Fix] mypage ui 수정
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageViewModel.kt
  IRecipe/app/src/main/res/layout/fragment_signup_first.xml
Labels: fix, 뉴아/이다윤

#56 [Feat] 마이페이지 레시피 보관함
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/MemberLikeRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/MemberWriteRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/mypage/MemberLikeResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/mypage/MemberWriteResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/mypage/MemberLikeService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/mypage/MemberWriteService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/MyPost.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/MemberLikeRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/MemberWriteRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/comment/CommentFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageRecipeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeLikeAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeLikeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeWriteAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeWriteFragment.kt
  IRecipe/app/src/main/res/drawable/bg_no_recipe.xml
  IRecipe/app/src/main/res/drawable/bg_recipe_btn_selector.xml
  IRecipe/app/src/main/res/layout/fragment_mypage_like.xml
  IRecipe/app/src/main/res/layout/fragment_mypage_recipe.xml
  IRecipe/app/src/main/res/layout/fragment_mypage_wirte.xml
  IRecipe/app/src/main/res/layout/fragment_signup_first.xml
Labels: feat, 뉴아/이다윤

#57 [Feat] 홈 랭킹 서버 연결
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/PostRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/home/GetPostRankingResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/home/GetPostRankingService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/PostRank.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/PostRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityPostAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeRankingAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/detail/HomeDetailAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/detail/HomeDetailFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/ic_recipe_ranking.xml
  IRecipe/app/src/main/res/drawable/img_recipe_item.png
  IRecipe/app/src/main/res/layout/fragment_home.xml
  IRecipe/app/src/main/res/layout/fragment_home_detail.xml
  IRecipe/app/src/main/res/layout/item_home.xml
  IRecipe/app/src/main/res/layout/item_recipe_ranking.xml
  IRecipe/app/src/main/res/values/colors.xml
  IRecipe/app/src/main/res/values/strings.xml
Labels: feat, 제로/조소윤

#60 [Feat]광고배너
  IRecipe/app/build.gradle.kts
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/write/WritePostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseFirstFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseFourthFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseSecondFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseThirdFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseVpAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageCenterFragment.kt
  IRecipe/app/src/main/res/drawable/ic_advertisement.jpeg
  IRecipe/app/src/main/res/layout/fragment_advertise_first.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_fourth.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_second.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_third.xml
  IRecipe/app/src/main/res/layout/fragment_home.xml
Labels: feat, 뉴아/이다윤

#65 [Feat] 냉장고 검색 서버 연결
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/RefrigeratorRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/refrigerator/RefrigeratorSearchResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/refrigerator/RefrigeratorSearchService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/RefrigeratorRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseFirstFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseSecondFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseThirdFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/RefrigeratorFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/RefrigeratorViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/process/RefrigeratorProcessViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/search/RefrigeratorSearchFragment.kt
  IRecipe/app/src/main/res/drawable/ic_advertise1.png
  IRecipe/app/src/main/res/drawable/ic_advertise2.png
  IRecipe/app/src/main/res/drawable/ic_advertise33.png
  IRecipe/app/src/main/res/drawable/ic_advertise4.png
  IRecipe/app/src/main/res/layout/fragment_advertise_first.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_fourth.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_second.xml
  IRecipe/app/src/main/res/layout/fragment_advertise_third.xml
  IRecipe/app/src/main/res/layout/fragment_home.xml
Labels: feat, 뉴아/이다윤

#67 [Feat]마이페이지 레시피보관함(내가쓴 글) 서버 재연결
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/MemberWriteRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/PostRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/community/WritePostResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/community/post/PostSearchResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/mypage/MemberWriteResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/community/PostSearchService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/MemberWriteRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/PostRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/post/PostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/advertise/AdvertiseThirdFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/login/LoginViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageCenterFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypagePersonalFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageRecipeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeWriteAdapter.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeWriteFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/refrigerator/RefrigeratorViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/util/MainActivity.kt
  IRecipe/app/src/main/res/drawable/bg_search_type.xml
  IRecipe/app/src/main/res/layout/fragment_community.xml
  IRecipe/app/src/main/res/menu/menu_search_type.xml
  IRecipe/app/src/main/res/values/strings.xml
Labels: feat, 뉴아/이다윤

#74 [Feat]커뮤니티 삭제
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/PostRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/community/postDelete/PostDeleteResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/community/PostDeleteService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/PostDetail.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/PostRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/ModalBottomSheetDeleteFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/ModalBottomSheetMyFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/post/PostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/MypageCenterFragment.kt
  IRecipe/app/src/main/res/layout/fragment_post.xml
Labels: feat, 뉴아/이다윤

#82 [Feat]커뮤니티 수정
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/ApiModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/module/RepositoryModule.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/repository/PostRepositoryImpl.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/request/community/PostUpdateRequest.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/response/community/postUpdate/PostUpdateResponse.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/data/remote/service/community/PostUpdateService.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/model/UpdatePost.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/domain/repository/PostRepository.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/CommunityFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/ModalBottomSheetMyFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/post/PostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/write/WritePostFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/write/WritePostViewModel.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/home/HomeFragment.kt
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/mypage/recipe/RecipeWriteFragment.kt
  IRecipe/app/src/main/res/layout/fragment_write_post.xml
Labels: feat, 뉴아/이다윤

#87 [Fix] 수정 콜백
  IRecipe/app/src/main/java/com/umcproject/irecipe/presentation/ui/community/ModalBottomSheetMyFragment.kt
Labels: fix, 뉴아/이다윤
